### ISSUE TITLE
Ajout des traductions des labels en allemand

### ISSUE THREAD

**Issue by Nikozens** [wavenet-be/CookieLaw#19]
Ci-dessous les traductions des labels en allemand.
bannerMessage, dialogNext, dialogPrevious, functionality.description et more_information.description sont des traductions provenant de google traduction. Les autres traductions nous ont été transmises par Total pour Proxifuel

    de:
    {
        bannerTitle: "Wir verwenden Cookies",
        bannerMessage: "Wir verwenden Cookies und andere Tracking-Technologien, um Ihre Navigation auf unserer Website zu verbessern, personalisierte Inhalte anzuzeigen, den Verkehr auf der Website zu analysieren und festzustellen, woher unsere Besucher kommen. Weitere Informationen zu Cookies, die mit dieser Website verlinkt sind, finden Sie in unserer [Cookie-Richtlinie] [cookiePolicy].",
        bannerOk: "OK",
        bannerPreferences: "Cookie-Einstellungen ändern",
        dialogNext: 'Folgenden',
        dialogPrevious: 'Vorhergehend',
        dialogSavePreferences: "Einstellungen speichern",
        dialogCheckboxAlways: "Immer",
        dialogCheckboxActive: "Aktiv",
        dialogCheckboxInactive: "Nicht aktiv"
    }

  "introduction":
    {
            "de": 
        {
            "tabTitle": "Ihrer Privatsphäre",
            "title": "Die Achtung Ihrer Privatsphäre ist uns wichtig",
            "description": [
                "Cookies sind kleine Dateien, die beim Besuch einer Website auf Ihrem Computer gespeichert werden. Wir verwenden sie zu unterschiedlichen Zwecken, insbesondere zur Verbesserung Ihrer Benutzererfahrung auf unserer Website (etwa zum Speichern der Anmeldedaten Ihres Benutzerzugangs oder von Angaben zu Werbung, die Ihnen bereits angezeigt wurde).",
                "Sie können Ihre Cookie-Einstellungen ändern und beim Surfen auf unserer Website bestimmte Cookies ablehnen. Sie können auch alle bereits auf Ihrem Computer gespeicherten Cookies löschen, aber bedenken Sie, dass Sie dann möglicherweise bestimmte Teile der Website nicht mehr nutzen können."
            ]
        }
        }

        "strictly-necessary":
    {
        "de": 
        {
            "title": "Unbedingt erforderliche Cookies",
            "description": [
                "Diese Cookies sind für den Zugriff auf die Dienste unserer Website unverzichtbar und ermöglichen Ihnen die Nutzung bestimmter Funktionen. Ohne diese Cookies können wir Ihnen bestimmte Dienste der Website nicht bereitstellen."
            ]
        }
    }
      "functionality":
    {
        "de":
        {
            "title": "Funktionscookies",
            "description": [
                "Diese Cookies werden verwendet, um Ihnen ein persönlicheres Erlebnis auf unserer Website zu bieten und um sich an die Entscheidungen zu erinnern, die Sie bei der Verwendung treffen. Beispielsweise können wir funktionsbezogene Cookies verwenden, um die ausgewählte Sprache oder Ihre Anmeldedaten zu speichern."
            ]
        }
    }
        "tracking":
    {
        "de":
        {
            "title": "Tracking- und Performance-Cookies",
            "description": [
                "Diese Cookies werden zum Sammeln von Informationen zur Analyse des Traffic auf unserer Website und darüber, wie diese von den Besuchern genutzt wird, verwendet. Diese Cookies können zum Beispiel die Verweildauer auf der Website oder die aufgerufenen Seiten speichern. Das hilft uns zu verstehen, wie wir unsere Website für Sie optimieren können. Mit diesen Informationen lässt sich die Identität eines einzelnen Besuchers nicht ermitteln."
            ]
        }
    }

        "more_information":
    {
        "de": 
        {
            "title": "Weitere Informationen",
            "description": [
                "Weitere Informationen zu den von uns verwendeten Cookies finden Sie in unserer [Cookie-Richtlinie] [cookiePolicy]."
            ]
        },
    }

**Comment by olibos** [comment]
Top, si tu veux, tu peux en faire une pull request 😉
